package com.zhang.blog.entity;

public class AdminUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin_user.admin_user_id
     *
     * @mbg.generated Fri Mar 13 22:10:26 CST 2020
     */
    private Integer adminUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin_user.login_user_name
     *
     * @mbg.generated Fri Mar 13 22:10:26 CST 2020
     */
    private String loginUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin_user.login_password
     *
     * @mbg.generated Fri Mar 13 22:10:26 CST 2020
     */
    private String loginPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin_user.nick_name
     *
     * @mbg.generated Fri Mar 13 22:10:26 CST 2020
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_admin_user.locked
     *
     * @mbg.generated Fri Mar 13 22:10:26 CST 2020
     */
    private Byte locked;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_admin_user.admin_user_id
     *
     * @return the value of tb_admin_user.admin_user_id
     *
     * @mbg.generated Fri Mar 13 22:10:26 CST 2020
     */
    public Integer getAdminUserId() {
        return adminUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_admin_user.admin_user_id
     *
     * @param adminUserId the value for tb_admin_user.admin_user_id
     *
     * @mbg.generated Fri Mar 13 22:10:26 CST 2020
     */
    public void setAdminUserId(Integer adminUserId) {
        this.adminUserId = adminUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_admin_user.login_user_name
     *
     * @return the value of tb_admin_user.login_user_name
     *
     * @mbg.generated Fri Mar 13 22:10:26 CST 2020
     */
    public String getLoginUserName() {
        return loginUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_admin_user.login_user_name
     *
     * @param loginUserName the value for tb_admin_user.login_user_name
     *
     * @mbg.generated Fri Mar 13 22:10:26 CST 2020
     */
    public void setLoginUserName(String loginUserName) {
        this.loginUserName = loginUserName == null ? null : loginUserName.trim();
    }

    @Override
    public String toString() {
        return "AdminUser{" +
                "adminUserId=" + adminUserId +
                ", loginUserName='" + loginUserName + '\'' +
                ", loginPassword='" + loginPassword + '\'' +
                ", nickName='" + nickName + '\'' +
                ", locked=" + locked +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_admin_user.login_password
     *
     * @return the value of tb_admin_user.login_password
     *
     * @mbg.generated Fri Mar 13 22:10:26 CST 2020
     */
    public String getLoginPassword() {
        return loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_admin_user.login_password
     *
     * @param loginPassword the value for tb_admin_user.login_password
     *
     * @mbg.generated Fri Mar 13 22:10:26 CST 2020
     */
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword == null ? null : loginPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_admin_user.nick_name
     *
     * @return the value of tb_admin_user.nick_name
     *
     * @mbg.generated Fri Mar 13 22:10:26 CST 2020
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_admin_user.nick_name
     *
     * @param nickName the value for tb_admin_user.nick_name
     *
     * @mbg.generated Fri Mar 13 22:10:26 CST 2020
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_admin_user.locked
     *
     * @return the value of tb_admin_user.locked
     *
     * @mbg.generated Fri Mar 13 22:10:26 CST 2020
     */
    public Byte getLocked() {
        return locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_admin_user.locked
     *
     * @param locked the value for tb_admin_user.locked
     *
     * @mbg.generated Fri Mar 13 22:10:26 CST 2020
     */
    public void setLocked(Byte locked) {
        this.locked = locked;
    }
}