package com.zhang.blog.dao;

import com.zhang.blog.entity.BlogTagRelation;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface BlogTagRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog_tag_relation
     *
     * @mbg.generated Fri Mar 13 22:10:26 CST 2020
     */
    int deleteByPrimaryKey(Long relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog_tag_relation
     *
     * @mbg.generated Fri Mar 13 22:10:26 CST 2020
     */
    int insert(BlogTagRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog_tag_relation
     *
     * @mbg.generated Fri Mar 13 22:10:26 CST 2020
     */
    int insertSelective(BlogTagRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog_tag_relation
     *
     * @mbg.generated Fri Mar 13 22:10:26 CST 2020
     */
    BlogTagRelation selectByPrimaryKey(Long relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog_tag_relation
     *
     * @mbg.generated Fri Mar 13 22:10:26 CST 2020
     */
    int updateByPrimaryKeySelective(BlogTagRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog_tag_relation
     *
     * @mbg.generated Fri Mar 13 22:10:26 CST 2020
     */
    int updateByPrimaryKey(BlogTagRelation record);

    List<Long> selectDistinctTagIds(Integer[] tagIds);

    int batchInsert(@Param("relationList") List<BlogTagRelation> blogTagRelationList);
}