package com.zhang.blog.dao;

import com.zhang.blog.entity.BlogCategory;
import com.zhang.blog.utils.PageQueryUtil;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Repository;

import java.util.List;


@Repository
public interface BlogCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog_category
     *
     * @mbg.generated Fri Mar 13 22:14:26 CST 2020
     */
    int deleteByPrimaryKey(Integer categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog_category
     *
     * @mbg.generated Fri Mar 13 22:14:26 CST 2020
     */
    int insert(BlogCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog_category
     *
     * @mbg.generated Fri Mar 13 22:14:26 CST 2020
     */
    int insertSelective(BlogCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog_category
     *
     * @mbg.generated Fri Mar 13 22:14:26 CST 2020
     */
    BlogCategory selectByPrimaryKey(Integer categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog_category
     *
     * @mbg.generated Fri Mar 13 22:14:26 CST 2020
     */
    int updateByPrimaryKeySelective(BlogCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog_category
     *
     * @mbg.generated Fri Mar 13 22:14:26 CST 2020
     */
    int updateByPrimaryKey(BlogCategory record);

    BlogCategory selectByCategoryName(String categoryName);

    List<BlogCategory> findCategoryList(PageQueryUtil pageUtil);

    List<BlogCategory> selectByCategoryIds(@Param("categoryIds") List<Integer> categoryIds);

    int getTotalCategories(PageQueryUtil pageUtil);

    int deleteBatch(Integer[] ids);
}