package com.zhang.blog.dao;

import com.zhang.blog.entity.Blog;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Repository;

@Repository
public interface BlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog
     *
     * @mbg.generated Sat Mar 14 19:59:33 CST 2020
     */
    int deleteByPrimaryKey(Long blogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog
     *
     * @mbg.generated Sat Mar 14 19:59:33 CST 2020
     */
    int insert(Blog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog
     *
     * @mbg.generated Sat Mar 14 19:59:33 CST 2020
     */
    int insertSelective(Blog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog
     *
     * @mbg.generated Sat Mar 14 19:59:33 CST 2020
     */
    Blog selectByPrimaryKey(Long blogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog
     *
     * @mbg.generated Sat Mar 14 19:59:33 CST 2020
     */
    int updateByPrimaryKeySelective(Blog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog
     *
     * @mbg.generated Sat Mar 14 19:59:33 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(Blog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_blog
     *
     * @mbg.generated Sat Mar 14 19:59:33 CST 2020
     */
    int updateByPrimaryKey(Blog record);
}